/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.backend.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;
import java.util.ArrayList;

import main.java.backend.conversion.translator.Translator;
import main.java.backend.conversion.parser.Parser;
import main.java.backend.conversion.Token;
import main.java.backend.conversion.TokenType;


@RestController
@RequestMapping("/tokens")
public class MyController {

    private String fileString = new String();
    private ArrayList<String> rawTokens = new ArrayList<>();

    @PutMapping("/parse")
    void parse(@RequestBody String newFileString)
    {
        Parser parser = new Parser();
        this.fileString = newFileString;
        this.rawTokens = parser.parse(this.fileString);
    }


    @GetMapping("/translate")
    ArrayList<Token> translate(){
        Translator translator = new Translator();
        translator.convertRawTokens(rawTokens);
        return translator.tokenizedFile;
    }
}