/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.backend.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;
import java.util.ArrayList;

import main.java.backend.conversion.translator.Translator;
import main.java.backend.conversion.parser.Parser;
import main.java.backend.conversion.Token;
import main.java.backend.conversion.TokenType;
import main.java.backend.comparison.Comparator;


@RestController
@RequestMapping("/tokens")
public class MyController {

    private String fileString1 = new String();
    private String fileString2 = new String();
    private ArrayList<String> rawTokens1 = new ArrayList<>();
    private ArrayList<String> rawTokens2 = new ArrayList<>();

    @PutMapping("/parse")
    void parse(@RequestBody String[] fileStrings)
    {
        Parser parser = new Parser();
        this.fileString1 = fileStrings[0];
        this.fileString2 = fileStrings[1];
        this.rawTokens1 = parser.parse(this.fileString1);
        this.rawTokens2 = parser.parse(this.fileString2);
    }


    @GetMapping("/compare")
    double translate(){
        Translator translator = new Translator();
        translator.convertRawTokens(rawTokens1);

        Translator translator2 = new Translator();
        translator2.convertRawTokens(rawTokens2);

        Comparator comparator = new Comparator();
        return comparator.compare(translator.tokenizedFile, translator2.tokenizedFile);
    }
}