/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.backend.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class MyController {

    @GetMapping("/home")
    String home(){
        return "Hello World!";
    }
}