/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import main.java.backend.conversion.driver.Driver;


public class App {

    public static void main(String[] args)
    {
        Driver driver = new Driver();
    }
}
