/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import main.java.backend.conversion.translator.Translator;
import java.util.ArrayList;

public class App {

    public static void main(String[] args)
    {
        ArrayList<String> rawTokens = new ArrayList();

        rawTokens.add("public");
        rawTokens.add("static");
        rawTokens.add("void");
        rawTokens.add("main");
        rawTokens.add("(");
        rawTokens.add("String");
        rawTokens.add("[");
        rawTokens.add("]");
        rawTokens.add("args");
        rawTokens.add(")");
        
        for(String rawToken : rawTokens)
        {
            System.out.println(rawToken);
        }
    }
}
