/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@RestController
@SpringBootApplication
public class App {

    @RequestMapping("/")
    String home(){
        return "Hello World!";
    }
    public static void main(String[] args)
    {
        SpringApplication.run(App.class, args);

    }
}
